from django.conf.urls import url
from Basic_app import views
from pathlib import Path

urlpatterns = [

    # The about page will be the homepage
    url(r'^$',views.AboutView.as_view(),name='about'),

    # Creating contact page
    url(r'^contact/$',views.Contact_View,name='contact_create'),

    # Contact confirmation page
    url(r'^contact/confirm/$',views.ContactConfirmed.as_view(),name='contact_confirm'),

    # List of Contacts page
    url(r'^contact/contact_list/$',views.ContactList.as_view(),name='contact_list'),

    # List of projects
    url(r'^projects/$',views.ProjectList.as_view(),name='project_list'),

    # New project creation,updating, and deleting
    url(r'^projects/new/$',views.ProjectCreate.as_view(),name='project_create'),
    url(r'^projects/(?P<pk>\d+)/edit/$',views.ProjectUpdate.as_view(),name='project_edit'),
    url(r'^projects/(?P<pk>\d+)/remove/$',views.ProjectDelete.as_view(),name='project_remove'),

    # Url for project detail generated by primary key
    url(r'^projects/(?P<pk>\d+)$',views.ProjectDetailView.as_view(),name='project_detail'),

]