from django.conf.urls import url
from Basic_app import views

urlpatterns = [

    # The about page will be the homepage
    url(r'^$',views.AboutView.as_view(),name='about'),

    # Creating contact page
    url(r'^contact/$',views.ContactView.as_view(),name='contact'),

    # Contact confirmation page
    url(r'^contact/confirm/$',views.ContactConfirmed.as_view(),name='contact_confirm'),

    # List of projects
    url(r'^projects/$',views.ProjectList.as_view(),name='project_list'),

    # New project create page
    url(r'^projects/new/$',views.ProjectCreate.as_view(),name='project_create'),

    # Url for project detail generated by primary key
    url(r'^projects/(?P<pk>\d+)$',views.ProjectDetailView.as_view(),name='project_detail'),
]