# Generated by Django 3.1.2 on 2020-11-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_pic',
        ),
    ]
