# Generated by Django 3.1.2 on 2020-11-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_app', '0002_remove_project_project_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(blank=True, upload_to='project_pic'),
        ),
    ]
