# Generated by Django 3.1.2 on 2020-11-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_app', '0004_auto_20201106_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(default='', upload_to='project_pic'),
        ),
    ]
