# Generated by Django 3.1.2 on 2020-11-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_app', '0008_auto_20201107_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
