# Generated by Django 3.1.2 on 2020-11-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_app', '0009_project_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
